### PR TITLE
Section 2 wikilinks etc

### PR DESCRIPTION
**Pull request by kingthorin**
- Removed un-necessary escaping.
- Fixed foot notes. (Now using `<sup>` tags in text and anchor tags at bottom.
- Add proper level 4/5 headings.
- Fixed images. Ref: https://help.github.com/en/articles/about-readmes#relative-links-and-image-paths-in-readme-files

See: OWASP/OWASP-Testing-Guide-v5#10

### CODE REVIEW

**Comment by kingthorin** [comment]
Note: I did a bunch of reading on image handling for github. Images unfortunately don't show in the previews I could get but supposedly the way it's been handled here will/should work :man_shrugging: :

**Comment by kingthorin** [comment]
@MatOwasp look ok?

**Comment by kingthorin** [comment]
@MatOwasp look ok?

**Comment by MatOwasp** [comment]
yep!

**Comment by kingthorin** [comment]
Thanks! (For both of them)

**Pull request merged**
