### PR TITLE
Section 1 Changes for v5

### PR DESCRIPTION
**Pull request by kingthorin**
- [ ] This PR handles the issue and requires no additional PRs.
- [x] You have validated the need for this change.
  - Per discussion here &gt; https://groups.google.com/a/owasp.org/forum/#!topic/testing-guide-project/XFsns2dbPj8

**What did this PR accomplish?**

* Moved contribution history to Appendix E.
* Added `Placeholder-TBC` to v5 lead-in sections.
* Set copyright to 2019 (can be updated further later if required).
* Started v5 Authors and Reviewers/Editors sections. (After this is merged we can ask/remind people to update this section).
* Implemented proper markdown headings and removed hyphen lines.
* Removed `<pre>` and `<br>` HTML tags.

Edit: At some point the contributors list(s) might have to change to tables, but we'll start like this for now and see how it goes.

### CODE REVIEW

**Comment by ManhNho** [comment]
I suggest that we can attached profile link (linkedin, twitter,..) at authors names. (When author request that)

**Comment by kingthorin** [comment]
So my intent is to get contributors to add themselves (then they can pick fullname, nick/handle, linked/not, etc). 
I added you and a few others I was aware of that already contributed (having checked PRs thus far, and just checked github profile). 

If you'd like a link, just let me know and I can include it on this PR :+1:

**Comment by ManhNho** [comment]
> So my intent is to get contributors to add themselves (then they can pick fullname, nick/handle, linked/not, etc).
> I added you and a few others I was aware of that already contributed (having checked PRs thus far, and just checked github profile).
> 
> If you'd like a link, just let me know and I can include it on this PR +1

Ok, I 'd like to add my linkedin profile https://www.linkedin.com/in/manhnho/ in author name: 
Manh Pham Tien.

Thank you so much!

**Comment by kingthorin** [comment]
TODO: Update per: https://github.com/OWASP/OWASP-Testing-Guide-v5/pull/63#issuecomment-497450143

**Comment by kingthorin** [comment]
Ya I kinda agree, however it's kind of "nice to have" content if this becomes a printed/PDFd product in the end like it has in the past.

We can always make the change in the end to drop it, I was just trying to clean it up and v5'ify it for now.

**Comment by ThunderSon** [comment]
Then I am with you on this. Should we wait for someone about the trademark? Do you know anyone that could help on it?

**Comment by kingthorin** [comment]
On the copyright year mark, for other projects I've been involved with we were told to maintain those. With an Open project it isn't terribly enforceable but there was some logic in keeping it (I don't recall the specifics). As for the license the repo license was specifically updated to CC-BY-SA 4.0 as agreed upon with OWASP Project Leadership (so I made this content align with that).

**Comment by MatOwasp** [comment]
Hi,
we use the standard OWASP Copyright as the last version 4. https://www.owasp.org/index.php/OWASP_Licenses, yes CC-BY-SA 4.0 is fine.
We put only Name and Surname of the authors (no links).
Thanks,
Mat

**Comment by kingthorin** [comment]
@MatOwasp did we purposefully avoid links in the past or was it just not an option? Do we want to avoid links here? (I'm happy to do it either way.)

**Comment by MatOwasp** [comment]
No, in v4 we have links, we have to use it in the descriptions. But I would like to avoid personal link (linkedin)

**Comment by kingthorin** [comment]
Ya ok that's what I meant. I'll trim those.

**Comment by kingthorin** [comment]
@ThunderSon you meant the product trademarks didn't you? (Not the copyright/license)

I can't speak to those, the only thing changed with that content was to fix the formatting of the bullets. I have no knowledge of the legalities of that content.

**Comment by ThunderSon** [comment]
Yep, the trademarks. I totally understand the license things, the trademarks are my concern before approving mainly

**Comment by kingthorin** [comment]
@MatOwasp any insight on the product trademarks?

**Comment by MatOwasp** [comment]
We mention it in the Frontispiece: 
https://github.com/OWASP/OWASP-Testing-Guide-v5/blob/master/document/1%20Frontispiece/1%20Frontispiece.md

Trademarks
Java, Java Web Server, and JSP are registered trademarks of Sun Microsystems, Inc.
Merriam-Webster is a trademark of Merriam-Webster, Inc.
Microsoft is a registered trademark of Microsoft Corporation.
Octave is a service mark of Carnegie Mellon University.
VeriSign and Thawte are registered trademarks of VeriSign, Inc.
Visa is a registered trademark of VISA USA.
OWASP is a registered trademark of the OWASP Foundation
All other products and company names may be trademarks of their respective owners. Use of a term in this document should not be regarded as affecting the validity of any trademark or service mark.

**Pull request merged**
