### PR TITLE
Section 1.2 Tweaks

### PR DESCRIPTION
**Pull request by kingthorin**
* Remove spurious slashes (`\`)
* Remove broken "Contact Us" links in EU details.
* Replaced HTML bold tags with markdown bolding.

### CODE REVIEW

**Comment by ThunderSon** [comment]
As a PR, it is valid, yet having HTML in the MD files is not a good practice. You feel like we should fix that too? From my side, I believe we should invest in more critical assets is this does not contribute to the project in any mean.

**Comment by kingthorin** [comment]
I'd rather not use the forced spacing/formatting of `<br>`, but haven't seen an appropriate alternative... I'll look into it a bit more.

**Comment by kingthorin** [comment]
Other usage such as in the "Core Values" section could be replaced with md, however usage for things such as images etc in order to control height/width seems unavoidable given how github handles/renders markdown. (I'm open to suggestions on that.)

**Comment by kingthorin** [comment]
Ok I found a solution to the `<br>` usage and replaced the HTML bold tags with markdown bolding.

**Pull request merged**
